use BI_NDS
go

CREATE TABLE Country (
	Id INT PRIMARY KEY IDENTITY(1,1),
	CountryId varchar(20) NOT NULL,
	Name VARCHAR(100),
	SourceId INT NOT NULL
)
GO

CREATE TABLE Region (
	Id INT PRIMARY KEY IDENTITY(1,1),
	RegionId varchar(20) NOT NULL,
	Name VARCHAR(100),
	CountryId INT NOT NULL,
	SourceId INT NOT NULL,

	CONSTRAINT FK_Region_Country FOREIGN KEY (CountryId)
	REFERENCES Country (Id)
)
GO

CREATE TABLE LAD (
	Id INT PRIMARY KEY IDENTITY(1,1),
	LADId varchar(20) NOT NULL,
	Name VARCHAR(100),
	RegionId INT NOT NULL,
	SourceId INT NOT NULL

	CONSTRAINT FK_LAD_Region FOREIGN KEY (RegionId)
	REFERENCES Region (Id)
)
GO

CREATE TABLE LSOA (
	Id INT PRIMARY KEY IDENTITY(1,1),
	LSOAId varchar(20) NOT NULL,
	Name VARCHAR(100),
	LADId INT NOT NULL,
	SourceId INT NOT NULL

	CONSTRAINT FK_LSOA_LAD FOREIGN KEY (LADId)
	REFERENCES LAD (Id)
)
GO



