use BI_NDS
go

CREATE TABLE Country (
	CountryId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100),
	SourceId INT NOT NULL
)
GO

CREATE TABLE Region (
	RegionId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100),
	CountryId INT NOT NULL,
	SourceId INT NOT NULL,

	CONSTRAINT FK_Region_Country FOREIGN KEY (CountryId)
	REFERENCES Country (CountryId)
)
GO

CREATE TABLE LAD (
	LADId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100),
	RegionId INT NOT NULL,
	SourceId INT NOT NULL

	CONSTRAINT FK_LAD_Region FOREIGN KEY (RegionId)
	REFERENCES Region (RegionId)
)
GO

CREATE TABLE LSOA (
	LSOAId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100),
	LADId INT NOT NULL,
	SourceId INT NOT NULL

	CONSTRAINT FK_LSOA_LAD FOREIGN KEY (LADId)
	REFERENCES LAD (LADId)
)
GO

